/******************************************************************************
 * Project        : Universal Autonomous AI Governance Operating System (UAIGOS)
 * Module         : EAORCS Decomposed Trust Engine
 * File           : CertificationEngine.js
 * Version        : 2026.1-LTS
 * Author         : Enterprise Architecture Authority & Systems Engineering
 * Organization   : Ujomor Systems & Enterprise Governance
 * Created Date   : 2026-08-01
 * Last Modified  : 2026-08-01
 * Classification : ENTERPRISE | RESTRICTED
 *
 * Governance:
 * - Security Reviewed
 * - Architecture Controlled
 * - Protocol Frozen
 * - Modularization Enforced
 *
 * Standards:
 * - ISO 27001
 * - SOC 2
 * - OWASP ASVS
 * - NIST
 *
 * Copyright (c) 2026 Ujomor Systems & Enterprise Governance. All Rights Reserved.
 ******************************************************************************/

const crypto = require('crypto');

/**
 * CertificationEngine
 * Automated Software Certification Authority for EAORCS.
 * Evaluates assurance readiness and trust score to issue cryptographically signed
 * Gold, Silver, or Bronze Enterprise Compliance Certificates.
 */
class CertificationEngine {
    constructor(options = {}) {
        this.issuer = options.issuer || 'EAORCS Software Certification Authority (UAIGOS v2026.1)';
        this.validityDays = options.validityDays || 90;
    }

    /**
     * Evaluates trust report eligibility for certification tiers
     * @param {Object} trustReport - Report generated by TrustScoreCalculator / ReadinessEngine
     * @returns {Object} Certification evaluation
     */
    evaluateCertification(trustReport = {}) {
        const trustScore = Number(trustReport.trustScore ?? trustReport.score ?? 0);
        const readiness = Number(trustReport.components?.readiness ?? trustReport.readinessScore ?? trustScore);
        const criticalGaps = Number(trustReport.criticalFailures ?? trustReport.criticalGaps ?? trustReport.penalties?.breakdown?.filter(b => b.factor === 'CRITICAL_SECURITY_GAPS')?.length ?? 0);

        let tier = 'NONE';
        let status = 'REJECTED';
        let reason = '';

        if (trustScore >= 95.0 && readiness >= 95.0 && criticalGaps === 0) {
            tier = 'GOLD';
            status = 'QUALIFIED';
            reason = 'Exceeds Gold tier criteria (Trust >= 95%, Readiness >= 95%, 0 critical gaps)';
        } else if (trustScore >= 85.0 && readiness >= 85.0 && criticalGaps === 0) {
            tier = 'SILVER';
            status = 'QUALIFIED';
            reason = 'Exceeds Silver tier criteria (Trust >= 85%, Readiness >= 85%, 0 critical gaps)';
        } else if (trustScore >= 70.0 && readiness >= 70.0 && criticalGaps === 0) {
            tier = 'BRONZE';
            status = 'QUALIFIED';
            reason = 'Exceeds Bronze tier criteria (Trust >= 70%, Readiness >= 70%)';
        } else {
            tier = 'NONE';
            status = 'REJECTED';
            reason = 'Fails minimum certification threshold (Trust < 70% or unresolved critical security gaps)';
        }

        return {
            status,
            tier,
            trustScore,
            readiness,
            criticalGaps,
            reason,
            evaluatedAt: new Date().toISOString()
        };
    }

    /**
     * Issues an Enterprise Software Certificate artifact signed cryptographically
     * @param {Object} trustReport - Trust score & readiness report
     * @param {Object} subjectInfo - Information about target system / artifact
     * @param {Object} [signerKeys] - Key pair or secret key for signing certificate
     * @returns {Object} Signed Certificate Manifest
     */
    async issueCertificate(trustReport = {}, subjectInfo = {}, signerKeys = {}) {
        if (trustReport && trustReport.artifactId && !subjectInfo.name) {
            subjectInfo = Object.assign({ name: trustReport.artifactId }, subjectInfo);
        }
        const evalResult = this.evaluateCertification(trustReport);
        if (evalResult.status !== 'QUALIFIED') {
            throw new Error(`Certification issue failed: System is not qualified (${evalResult.reason})`);
        }

        const issuedAt = new Date();
        const expiresAt = new Date(issuedAt.getTime() + (this.validityDays * 24 * 60 * 60 * 1000));
        const certificateId = `EAORCS-CERT-${evalResult.tier}-${Date.now()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;

        const certPayload = {
            certificateId,
            version: '2.0.0',
            tier: evalResult.tier,
            issuer: this.issuer,
            subject: {
                name: subjectInfo.name || 'EAORCS Target Application',
                version: subjectInfo.version || '1.0.0',
                repository: subjectInfo.repository || 'workspace://local',
                commitHash: subjectInfo.commitHash || 'HEAD',
                merkleRoot: trustReport.merkleRoot || subjectInfo.merkleRoot || '0x0'
            },
            trustMetrics: {
                trustScore: evalResult.trustScore,
                readinessScore: evalResult.readiness,
                evidenceConfidence: trustReport.components?.evidenceConfidence ?? 1.0,
                statisticalConfidence: trustReport.components?.statisticalConfidence ?? 1.0
            },
            issuedAt: issuedAt.toISOString(),
            expiresAt: expiresAt.toISOString(),
            classification: 'ENTERPRISE_GOVERNED'
        };

        // Compute signature
        const canonicalString = JSON.stringify(certPayload);
        let signature;

        if (signerKeys.privateKey) {
            // Ed25519 or RSA sign
            signature = crypto.sign(null, Buffer.from(canonicalString), signerKeys.privateKey).toString('hex');
        } else {
            // Default HMAC-SHA256 signature
            const secret = signerKeys.secretKey || 'EAORCS_CERTIFICATE_SECRET_KEY_2026';
            signature = crypto.createHmac('sha256', secret).update(canonicalString).digest('hex');
        }

        return {
            certificate: certPayload,
            signatureAlgorithm: signerKeys.privateKey ? 'Ed25519' : 'HMAC-SHA256',
            signature
        };
    }

    /**
     * Verifies an issued certificate artifact
     * @param {Object} certificateManifest - Certificate payload & signature object
     * @param {Object} [verifierKeys] - Verification key or secret
     * @returns {Object} Verification result
     */
    verifyCertificate(certificateManifest = {}, verifierKeys = {}) {
        if (!certificateManifest.certificate || !certificateManifest.signature) {
            return { valid: false, reason: 'Invalid certificate manifest structure' };
        }

        const cert = certificateManifest.certificate;
        const now = new Date().getTime();
        const expires = new Date(cert.expiresAt).getTime();

        if (now > expires) {
            return { valid: false, reason: 'Certificate has expired', certificateId: cert.certificateId };
        }

        const canonicalString = JSON.stringify(cert);
        let isValid = false;

        if (certificateManifest.signatureAlgorithm === 'Ed25519' && verifierKeys.publicKey) {
            isValid = crypto.verify(null, Buffer.from(canonicalString), verifierKeys.publicKey, Buffer.from(certificateManifest.signature, 'hex'));
        } else {
            const secret = verifierKeys.secretKey || 'EAORCS_CERTIFICATE_SECRET_KEY_2026';
            const expectedSig = crypto.createHmac('sha256', secret).update(canonicalString).digest('hex');
            isValid = (expectedSig === certificateManifest.signature);
        }

        return {
            valid: isValid,
            certificateId: cert.certificateId,
            tier: cert.tier,
            trustScore: cert.trustMetrics.trustScore,
            issuer: cert.issuer,
            expiresAt: cert.expiresAt,
            verifiedAt: new Date().toISOString()
        };
    }
}

module.exports = CertificationEngine;
