/******************************************************************************
 * Project        : Enterprise Autonomous Operational Readiness & Certification System (EAORCS)
 * Module         : Centralized Branding Engine
 * File           : CentralizedBrandingEngine.js
 * Version        : 2026.3.0-RC1
 * Author         : Platform Design System & Branding Authority
 * Organization   : Air Roofers Platform Ecosystem & Ujomor Systems
 * Created Date   : 2026-08-06
 * Last Modified  : 2026-08-06
 * Classification : GOVERNMENT | ENTERPRISE | RESTRICTED
 *
 * Governance:
 * - Architecture Authority Approved — ENHANCEMENT (Foundation-Locked)
 * - White-Label Branding: ENTERPRISE+ ONLY (server-side gated)
 * - Branding Resolution Cascade: Customer → Tenant → Platform → Fallback
 *
 * Copyright (c) 2026 Air Roofers Platform Ecosystem & Ujomor Systems
 * All Rights Reserved.
 ******************************************************************************/

'use strict';

const crypto = require('crypto');

/**
 * EAORCS Platform Defaults
 * Used as the final resolved fallback before the hardcoded SVG fallback.
 */
const PLATFORM_DEFAULTS = Object.freeze({
  organizationName:    'EAORCS — Enterprise Software Trust Platform',
  primaryColor:        '#0f172a',   // Slate-900
  accentColor:         '#6366f1',   // Indigo-500
  backgroundColor:     '#ffffff',
  fontFamily:          'Inter, system-ui, sans-serif',
  logoUrl:             null,        // Will trigger SVG fallback if still null
  faviconUrl:          null,
  reportFooter:        'Powered by EAORCS — Enterprise Software Trust Platform',
  reportWatermark:     'CONFIDENTIAL — Software Trust Assessment',
  portalTheme:         'EAORCS_DEFAULT',
});

/** Inline SVG fallback logo — always available, never fails */
const FALLBACK_LOGO_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="120" height="40" viewBox="0 0 120 40">
  <rect width="120" height="40" rx="6" fill="#0f172a"/>
  <text x="10" y="26" font-family="Inter,sans-serif" font-size="14" font-weight="700" fill="#6366f1">EAORCS</text>
</svg>`;

const FALLBACK_FAVICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="6" fill="#0f172a"/>
  <text x="7" y="22" font-family="Inter,sans-serif" font-size="13" font-weight="800" fill="#6366f1">E</text>
</svg>`;

/**
 * BrandingProfile
 * Resolved brand context for a given tenant and customer.
 */
class BrandingProfile {
  constructor(resolved) {
    this.organizationName = resolved.organizationName;
    this.primaryColor     = resolved.primaryColor;
    this.accentColor      = resolved.accentColor;
    this.backgroundColor  = resolved.backgroundColor;
    this.fontFamily       = resolved.fontFamily;
    this.logoUrl          = resolved.logoUrl;
    this.faviconUrl       = resolved.faviconUrl;
    this.reportFooter     = resolved.reportFooter;
    this.reportWatermark  = resolved.reportWatermark;
    this.portalTheme      = resolved.portalTheme;
    this.resolvedAt       = new Date().toISOString();
    this.resolutionPath   = resolved._resolutionPath || [];
  }

  /**
   * Returns an inline SVG logo — always resolves, never throws.
   */
  getLogoSvg() {
    // In production: fetch from logoUrl and return. Here: return platform default SVG.
    return FALLBACK_LOGO_SVG;
  }

  getFaviconSvg() {
    return FALLBACK_FAVICON_SVG;
  }

  /**
   * Generates a CSS theme string for portal injection.
   */
  toCssTheme() {
    return `/* EAORCS Brand Theme — Auto-generated by CentralizedBrandingEngine */
:root {
  --brand-primary:       ${this.primaryColor};
  --brand-accent:        ${this.accentColor};
  --brand-background:    ${this.backgroundColor};
  --brand-font-family:   ${this.fontFamily};
  --brand-org-name:      "${this.organizationName}";
}

body { font-family: var(--brand-font-family); background-color: var(--brand-background); }
.eaorcs-nav { background-color: var(--brand-primary); }
.eaorcs-accent { color: var(--brand-accent); }
.eaorcs-button-primary { background-color: var(--brand-accent); color: #fff; border-radius: 6px; padding: 8px 16px; border: none; font-weight: 600; }
.eaorcs-badge { background-color: var(--brand-accent); color: #fff; border-radius: 9999px; padding: 2px 8px; font-size: 12px; font-weight: 700; }
.eaorcs-report-header { background-color: var(--brand-primary); color: #fff; padding: 24px; }
.eaorcs-report-footer::after { content: "${this.reportFooter}"; }
`;
  }

  /**
   * Returns report header metadata for PDF/HTML report injection.
   */
  toReportHeader() {
    return {
      organizationName: this.organizationName,
      logoSvg:          this.getLogoSvg(),
      primaryColor:     this.primaryColor,
      accentColor:      this.accentColor,
      footer:           this.reportFooter,
      watermark:        this.reportWatermark,
      generatedAt:      new Date().toISOString(),
    };
  }
}

/**
 * CentralizedBrandingEngine
 *
 * Resolves brand configuration through a 4-level cascade:
 *   Customer Config → Tenant Config → EAORCS Platform Defaults → Hardcoded Fallback SVG
 *
 * Ensures the missing-logo problem is architecturally impossible:
 * the engine always resolves a complete branding profile.
 *
 * Scope (this phase):
 *   ✅ Report & PDF branding
 *   ✅ Portal CSS theme generation
 *   ⬜ Email branding (deferred to Phase 5)
 */
class CentralizedBrandingEngine {
  constructor(options = {}) {
    this.options = options;
    this._customerConfigs = new Map();  // customerId -> BrandConfig
    this._tenantConfigs   = new Map();  // tenantId -> { customerId, BrandConfig }
    this._resolvedCache   = new Map();  // cacheKey -> BrandingProfile
  }

  /**
   * Registers a customer-level brand configuration.
   * Customer-level branding is the highest-priority override (e.g., reseller or partner).
   * ENTERPRISE+ only — server-side enforcement.
   *
   * @param {string} customerId
   * @param {object} config - Brand configuration overrides
   * @returns {object} Registration receipt
   */
  registerCustomerBranding(customerId, config) {
    this._validateConfig(config);
    this._customerConfigs.set(customerId, { ...config, registeredAt: new Date().toISOString() });
    this._resolvedCache.clear(); // Invalidate cache on config change
    return { customerId, registered: true, configKeys: Object.keys(config) };
  }

  /**
   * Registers a tenant-level brand configuration.
   * @param {string} tenantId
   * @param {string} customerId - Parent customer ID for cascade lookup
   * @param {object} config - Tenant brand configuration overrides
   * @returns {object} Registration receipt
   */
  registerTenantBranding(tenantId, customerId, config) {
    this._validateConfig(config);
    this._tenantConfigs.set(tenantId, { customerId, config: { ...config, registeredAt: new Date().toISOString() } });
    this._resolvedCache.clear();
    return { tenantId, customerId, registered: true };
  }

  /**
   * Resolves a complete BrandingProfile for a given tenant via 4-level cascade.
   *
   * Cascade:
   *   Level 1 — Customer Config (highest priority, ENTERPRISE+)
   *   Level 2 — Tenant Config
   *   Level 3 — EAORCS Platform Defaults
   *   Level 4 — Hardcoded Fallback SVG (always succeeds)
   *
   * @param {string} tenantId
   * @returns {BrandingProfile}
   */
  resolve(tenantId) {
    const cacheKey = tenantId;
    if (this._resolvedCache.has(cacheKey)) {
      return this._resolvedCache.get(cacheKey);
    }

    const resolutionPath = [];
    let merged = { ...PLATFORM_DEFAULTS };
    merged._resolutionPath = resolutionPath;

    // Level 2: Tenant Config
    const tenantEntry = this._tenantConfigs.get(tenantId);
    if (tenantEntry) {
      resolutionPath.push('TENANT_CONFIG');
      merged = this._merge(merged, tenantEntry.config);

      // Level 1: Customer Config (via tenant's parent customer)
      const customerConfig = this._customerConfigs.get(tenantEntry.customerId);
      if (customerConfig) {
        resolutionPath.push('CUSTOMER_CONFIG');
        merged = this._merge(merged, customerConfig);
      }
    } else {
      resolutionPath.push('PLATFORM_DEFAULTS');
    }

    // Level 4: Ensure logo/favicon always resolve to fallback SVG reference if null
    if (!merged.logoUrl)    { merged.logoUrl    = 'data:image/svg+xml;base64,' + Buffer.from(FALLBACK_LOGO_SVG).toString('base64'); resolutionPath.push('FALLBACK_LOGO_SVG'); }
    if (!merged.faviconUrl) { merged.faviconUrl = 'data:image/svg+xml;base64,' + Buffer.from(FALLBACK_FAVICON_SVG).toString('base64'); resolutionPath.push('FALLBACK_FAVICON_SVG'); }

    merged._resolutionPath = resolutionPath;
    const profile = new BrandingProfile(merged);
    this._resolvedCache.set(cacheKey, profile);
    return profile;
  }

  /**
   * Generates a complete portal CSS theme for a tenant.
   * @param {string} tenantId
   * @returns {string} CSS string ready for portal injection
   */
  getPortalCssTheme(tenantId) {
    return this.resolve(tenantId).toCssTheme();
  }

  /**
   * Returns the report header metadata for a tenant's reports.
   * @param {string} tenantId
   * @returns {object} Report header metadata
   */
  getReportHeader(tenantId) {
    return this.resolve(tenantId).toReportHeader();
  }

  /**
   * Validates a brand configuration object.
   */
  _validateConfig(config) {
    if (!config || typeof config !== 'object') throw new Error('CentralizedBrandingEngine: config must be an object.');
    const hexColorPattern = /^#[0-9a-fA-F]{3,8}$/;
    if (config.primaryColor && !hexColorPattern.test(config.primaryColor)) {
      throw new Error('CentralizedBrandingEngine: primaryColor must be a valid hex color.');
    }
    if (config.accentColor && !hexColorPattern.test(config.accentColor)) {
      throw new Error('CentralizedBrandingEngine: accentColor must be a valid hex color.');
    }
  }

  _merge(base, override) {
    const merged = { ...base };
    for (const [key, val] of Object.entries(override)) {
      if (val !== null && val !== undefined && key !== '_resolutionPath' && key !== 'registeredAt') {
        merged[key] = val;
      }
    }
    return merged;
  }

  invalidateCache(tenantId) {
    if (tenantId) this._resolvedCache.delete(tenantId);
    else this._resolvedCache.clear();
  }

  getEngineStatus() {
    return {
      initialized: true,
      registeredCustomers: this._customerConfigs.size,
      registeredTenants: this._tenantConfigs.size,
      resolvedCacheSize: this._resolvedCache.size,
      fallbackLogoAvailable: true,
      fallbackFaviconAvailable: true,
    };
  }
}

module.exports = CentralizedBrandingEngine;
module.exports.CentralizedBrandingEngine = CentralizedBrandingEngine;
module.exports.BrandingProfile = BrandingProfile;
module.exports.PLATFORM_DEFAULTS = PLATFORM_DEFAULTS;
