/******************************************************************************
 * Project        : Universal Autonomous AI Governance Operating System (UAIGOS)
 * Module         : EAORCS Specification Intelligence Engine (Stream A)
 * File           : RequirementParser.js
 * Version        : 2026.1-LTS (v1.0.0-FROZEN)
 * Author         : Ujomor Systems & Enterprise Governance Authority
 * Organization   : Ujomor Systems & Enterprise Governance
 * Created Date   : 2026-08-01
 * Last Modified  : 2026-08-01
 * Classification : ENTERPRISE | RESTRICTED
 *
 * Governance:
 * - Security Reviewed
 * - Architecture Controlled
 * - Protocol Frozen
 * - Modularization Enforced
 * - Corporate Policy Governed
 *
 * Standards:
 * - ISO 27001
 * - SOC 2
 * - OWASP ASVS
 * - NIST
 *
 * Copyright (c) 2026 Ujomor Systems & Enterprise Governance. All Rights Reserved.
 ******************************************************************************/

class RequirementParser {
    constructor(options = {}) {
        this.options = options;
    }

    /**
     * Extracts granular requirements from a Blueprint AST.
     * @param {object} blueprintAst Structured AST generated by BlueprintParser.
     * @returns {Array<{ id: string, title: string, type: 'FUNCTIONAL'|'NON_FUNCTIONAL'|'SECURITY'|'COMPLIANCE', description: string, acceptanceCriteria: Array<string>, priority: 'CRITICAL'|'HIGH'|'MEDIUM'|'LOW' }>}
     */
    extractRequirements(blueprintAst) {
        if (!blueprintAst || typeof blueprintAst !== 'object') {
            throw new Error('Invalid Blueprint AST provided to extractRequirements');
        }

        const sections = blueprintAst.sections || [];
        const requirements = [];
        const seenIds = new Set();
        let counter = 1;

        for (const section of sections) {
            const sectionReqs = this._extractFromSection(section, blueprintAst, counter);
            for (const req of sectionReqs) {
                if (!seenIds.has(req.id)) {
                    seenIds.add(req.id);
                    requirements.push(req);
                    counter++;
                }
            }
        }

        // Fallback: If no requirements were extracted from sections, create at least one from AST overview
        if (requirements.length === 0) {
            const fallbackId = `REQ-${(blueprintAst.type || 'SPEC').toUpperCase()}-01`;
            const fallbackReq = {
                id: fallbackId,
                title: blueprintAst.title || 'Specification Primary Requirement',
                type: this._classifyType(blueprintAst.title, blueprintAst.type),
                description: blueprintAst.title || 'Primary system specification requirement.',
                acceptanceCriteria: ['Requirement must be implemented and verified by test suite.'],
                priority: 'HIGH'
            };
            requirements.push(fallbackReq);
        }

        blueprintAst.requirements = requirements;
        return requirements;
    }

    /**
     * Static helper for direct invocation.
     */
    static extractRequirements(blueprintAst) {
        return new RequirementParser().extractRequirements(blueprintAst);
    }

    _extractFromSection(section, ast, startCounter) {
        const reqs = [];
        const text = (section.title + '\n' + (section.content || '')).trim();

        // Pattern matching explicit requirement codes like REQ-01, REQ-SPEC-01, REQ-SEC-100
        const reqPattern = /(REQ-[A-Z0-9_-]+)[\s:]*([^\n]+)?/gi;
        let match;
        let foundExplicit = false;

        while ((match = reqPattern.exec(text)) !== null) {
            foundExplicit = true;
            const reqId = match[1].toUpperCase();
            const reqTitle = (match[2] || section.title).trim();

            const description = this._extractDescription(text, match.index, reqTitle);
            const acceptanceCriteria = this._extractAcceptanceCriteria(section, text);
            const type = this._classifyType(reqId + ' ' + reqTitle + ' ' + description, section.title);
            const priority = this._classifyPriority(reqId + ' ' + reqTitle + ' ' + description);

            reqs.push({
                id: reqId,
                title: reqTitle,
                type,
                description: description || reqTitle,
                acceptanceCriteria: acceptanceCriteria.length > 0 ? acceptanceCriteria : [`${reqId} criteria met`],
                priority
            });
        }

        // If no explicit REQ- tags were found, check if section contains requirement indicators
        if (!foundExplicit) {
            const hasModalities = /\b(MUST|SHALL|SHOULD|REQUIRED)\b/i.test(text);
            const isEndpoint = /^(GET|POST|PUT|DELETE|PATCH)\s+\//i.test(section.title);

            if (hasModalities || isEndpoint || (section.bullets && section.bullets.length > 0)) {
                const reqId = `REQ-${(ast.type || 'SPEC').toUpperCase()}-${String(startCounter + reqs.length).padStart(2, '0')}`;
                const type = this._classifyType(text, section.title);
                const priority = this._classifyPriority(text);
                const acceptanceCriteria = this._extractAcceptanceCriteria(section, text);

                reqs.push({
                    id: reqId,
                    title: section.title,
                    type,
                    description: (section.content || section.title).slice(0, 300),
                    acceptanceCriteria: acceptanceCriteria.length > 0 ? acceptanceCriteria : [`Verification of ${section.title}`],
                    priority
                });
            }
        }

        return reqs;
    }

    _extractDescription(text, matchIndex, title) {
        const afterMatch = text.slice(matchIndex).split('\n');
        const descLines = [];

        for (let i = 0; i < Math.min(afterMatch.length, 5); i++) {
            const line = afterMatch[i].trim();
            if (line && !line.toUpperCase().includes('ACCEPTANCE') && !line.toUpperCase().includes('VERIFIED BY')) {
                descLines.push(line);
            }
        }

        return descLines.join(' ') || title;
    }

    _extractAcceptanceCriteria(section, text) {
        const criteria = [];

        if (section.bullets && section.bullets.length > 0) {
            for (const b of section.bullets) {
                if (/^(Given|When|Then|Verify|Ensure|Must|Check|AC:)/i.test(b) || b.length > 10) {
                    criteria.push(b);
                }
            }
        }

        const lines = text.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();
            if (/^(AC|Criteria|Acceptance|Given|When|Then):/i.test(trimmed)) {
                criteria.push(trimmed.replace(/^(AC|Criteria|Acceptance|Given|When|Then):\s*/i, ''));
            }
        }

        return criteria;
    }

    _classifyType(text, contextTitle = '') {
        const combined = (text + ' ' + contextTitle).toLowerCase();

        if (/\b(security|auth|jwt|encrypt|tls|ssl|crypto|token|secret|password|rbac|permission|role|vulnerability|zero-trust)\b/i.test(combined)) {
            return 'SECURITY';
        }
        if (/\b(compliance|gdpr|iso|soc2|owasp|audit|governance|policy|retention|regulatory|legal)\b/i.test(combined)) {
            return 'COMPLIANCE';
        }
        if (/\b(performance|latency|throughput|scaling|scalable|concurrency|sla|availability|speed|load|memory)\b/i.test(combined)) {
            return 'NON_FUNCTIONAL';
        }

        return 'FUNCTIONAL';
    }

    _classifyPriority(text) {
        const upper = text.toUpperCase();

        if (upper.includes('CRITICAL') || upper.includes('MUST HAVE') || upper.includes('SEV-1')) {
            return 'CRITICAL';
        }
        if (upper.includes('HIGH') || upper.includes('MUST') || upper.includes('SHALL')) {
            return 'HIGH';
        }
        if (upper.includes('LOW') || upper.includes('MAY') || upper.includes('OPTIONAL')) {
            return 'LOW';
        }

        return 'MEDIUM';
    }
}

module.exports = RequirementParser;
