'use strict';

const assert = require('assert');
const BlueprintCompilerEngine = require('../../engine/spec/BlueprintCompilerEngine');

async function runTest() {
    console.log('Running test for BlueprintCompilerEngine (Stream P2)...');
    const engine = new BlueprintCompilerEngine();
    const result = await engine.run();

    assert.strictEqual(result.engineType, 'BLUEPRINT_COMPILER_ENGINE');
    assert.strictEqual(result.compiledRequirementNodesCount, 2480);
    assert.strictEqual(result.compiledDomainModelsCount, 140);
    assert.strictEqual(result.autoGeneratedSdkContractsCount, 38);
    assert.strictEqual(result.zeroManualSyncErosionScorePercent, 100.0);
    assert.strictEqual(result.blueprintCompilerStatus, 'BLUEPRINT_COMPILER_VERIFIED');

    console.log('Stream P2 test passed.');
}

if (require.main === module) {
    runTest().catch(err => {
        console.error(err);
        process.exit(1);
    });
}

module.exports = runTest;
