/******************************************************************************
 * Project        : EAORCS - Enterprise Autonomous Operation & Regulatory Compliance System
 * Module         : Air Roofers Platform Integration Compliance Reporter
 * File           : IntegrationComplianceReporter.js
 * Version        : 2026.1.0-LTS
 * Author         : Air Roofers Architecture Authority / Ujomor Systems
 * Organization   : Air Roofers / Ujomor Systems
 * Created Date   : 2026-08-01
 * Last Modified  : 2026-08-01
 * Classification : ENTERPRISE | GOVERNMENT
 *
 * Governance:
 * - AI Governed
 * - Security Reviewed
 * - Architecture Controlled
 * - Protocol Frozen
 * - Modularization Enforced
 *
 * Standards:
 * - ISO 27001
 * - SOC 2
 * - OWASP ASVS
 * - NIST
 *
 * Copyright (c) 2026 Air Roofers / Ujomor Systems
 * All Rights Reserved.
 ******************************************************************************/

class IntegrationComplianceReporter {
  static generateReport(input) {
    let reportData;
    if (input && Array.isArray(input.results) && input.summary) {
      reportData = input;
    } else if (Array.isArray(input)) {
      const results = input;
      const pass = results.filter(r => r.status === 'PASS').length;
      const warn = results.filter(r => r.status === 'WARN').length;
      const fail = results.filter(r => r.status === 'FAIL').length;
      reportData = {
        productName: 'EAORCS',
        timestamp: new Date().toISOString(),
        results,
        summary: {
          total: results.length,
          pass,
          warn,
          fail,
          compliant: fail === 0
        }
      };
    } else {
      reportData = {
        productName: input?.productName || 'Unknown Product',
        timestamp: new Date().toISOString(),
        results: [],
        summary: { total: 0, pass: 0, warn: 0, fail: 0, compliant: false }
      };
    }

    const json = JSON.stringify(reportData, null, 2);

    const rows = reportData.results.map(r => {
      let statusBadge = r.status;
      if (r.status === 'PASS') statusBadge = '🟢 PASS';
      else if (r.status === 'WARN') statusBadge = '🟡 WARN';
      else if (r.status === 'FAIL') statusBadge = '🔴 FAIL';

      return `| \`${r.id}\` | ${r.name} | ${statusBadge} | ${r.detail} |`;
    }).join('\n');

    const overallBadge = reportData.summary.compliant ? '🟢 COMPLIANT' : '🔴 NON-COMPLIANT';

    const markdown = `# Air Roofers Platform Integration Compliance Report

**Product:** \`${reportData.productName}\`  
**Timestamp:** \`${reportData.timestamp}\`  
**Overall Compliance Status:** **${overallBadge}**

---

## Executive Summary

- **Total Requirements Evaluated:** \`${reportData.summary.total}\`
- **Passed:** \`${reportData.summary.pass}\`
- **Warnings:** \`${reportData.summary.warn}\`
- **Failed:** \`${reportData.summary.fail}\`
- **Compliance Rate:** \`${reportData.summary.total > 0 ? ((reportData.summary.pass / reportData.summary.total) * 100).toFixed(1) : 0}%\`

---

## Detailed Integration Compliance Matrix

| ID | Integration Requirement | Status | Verification Detail |
|---|---|---|---|
${rows}

---

*Report automatically generated by Air Roofers Integration Compliance Engine v2026.1.0-LTS*
`;

    return { json, markdown };
  }
}

module.exports = IntegrationComplianceReporter;
